//
//  OnfonMediaSMSGateway
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "Configuration.h"

/** The base Uri for API calls */
NSString* Configuration_BaseUri = @"https://api.onfonmedia.co.ke/v1/sms";

/** Network Layer Access Key */
/** Replace the value of AccessKey with an appropriate value */
NSString* Configuration_AccessKey = @"ACCESS_KEY";

/** Used for authentication purpose and pass this parameter in URL encoded format. */
/** Replace the value of ApiKey with an appropriate value */
NSString* Configuration_ApiKey = @"API_KEY";

/** Used for authentication purpose and pass this parameter in URL encoded format. */
/** Replace the value of ClientId with an appropriate value */
NSString* Configuration_ClientId = @"CLIENT_ID";

