//
//  OnfonMediaSMSGateway
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef OnfonMediaSMSGateway_Configuration_h
#define OnfonMediaSMSGateway_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

/** Network Layer Access Key */
/** extern reference to the config variable AccessKey */
extern NSString* Configuration_AccessKey;

/** Used for authentication purpose and pass this parameter in URL encoded format. */
/** extern reference to the config variable ApiKey */
extern NSString* Configuration_ApiKey;

/** Used for authentication purpose and pass this parameter in URL encoded format. */
/** extern reference to the config variable ClientId */
extern NSString* Configuration_ClientId;

#endif
