//
//  OnfonMediaSMSGateway
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "NSDate+extension.h"

@interface CampaignController : BaseController

/**
* Completion block definition for asynchronous call to Get Campaign Message Status */
typedef void (^CompletedGetCampaignMessageStatus)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get Campaign Message Status
* @param    campaignId    Required parameter: First user have to call Get Campaigns api for CampaignId
*/
- (void) getCampaignMessageStatusAsyncWithCampaignId:(int) campaignId
                completionBlock:(CompletedGetCampaignMessageStatus) onCompleted;

/**
* Completion block definition for asynchronous call to Get Campaigns */
typedef void (^CompletedGetCampaigns)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get Campaigns
* @param    enddate    Required parameter: Date format must be in yyyy-mm-dd
* @param    fromdate    Required parameter: Date format must be in yyyy-mm-dd
* @param    length    Required parameter: Ending index value to fetch the campaign detail.
* @param    start    Required parameter: Starting index value to fetch the campaign detail.
*/
- (void) getCampaignsAsyncWithEnddate:(NSDate*) enddate
                fromdate:(NSDate*) fromdate
                length:(int) length
                start:(int) start
                completionBlock:(CompletedGetCampaigns) onCompleted;

@end