//
//  OnfonMediaSMSGateway
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface TemplateController : BaseController

/**
* Completion block definition for asynchronous call to Get Template List */
typedef void (^CompletedGetTemplateList)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get Template List
*/
- (void) getTemplateListWithCompletionBlock:(CompletedGetTemplateList) onCompleted;

/**
* Completion block definition for asynchronous call to Create New Template */
typedef void (^CompletedPostCreateNewTemplate)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Create New Template
* @param    messageTemplate    Required parameter: Template text.
* @param    templateName    Required parameter: Name of template
*/
- (void) createNewTemplateAsyncWithMessageTemplate:(NSString*) messageTemplate
                templateName:(NSString*) templateName
                completionBlock:(CompletedPostCreateNewTemplate) onCompleted;

/**
* Completion block definition for asynchronous call to Update Template */
typedef void (^CompletedPutUpdateTemplate)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Update Template
* @param    messageTemplate    Required parameter: Template text.
* @param    templateName    Required parameter: Name of template
* @param    mid    Required parameter: id of template
*/
- (void) updateTemplateAsyncWithMessageTemplate:(NSString*) messageTemplate
                templateName:(NSString*) templateName
                mid:(int) mid
                completionBlock:(CompletedPutUpdateTemplate) onCompleted;

/**
* Completion block definition for asynchronous call to Delete Template */
typedef void (^CompletedDeleteTemplate)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Delete Template
* @param    mid    Required parameter: id of template
*/
- (void) deleteTemplateAsyncWithId:(int) mid
                completionBlock:(CompletedDeleteTemplate) onCompleted;

@end